version: '2'

services:
  openfire:
    restart: unless-stopped
    image: gizmotronic/openfire:latest
    hostname: jabber.example.com
    ports:
      - 9090:9090
      - 5222:5222
      - 7777:7777
    volumes:
      - ./databases/openfire:/var/lib/openfire
      - ./logs/openfire:/var/log/openfire/
    links:
      - postgres:db

  postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
      - ./databases/postgresql:/var/lib/postgresql/data/pgdata
      - ./logs/postgresql:/var/log/postgresql

